# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# General overrides used across formulas in the org
{%- set LLL = 'Layout/LineLength' %}
{{ LLL }}:
  {%- set rbcp_LLL = rubocop.Cops.get(LLL) %}
  {%- if rbcp_LLL.Max == rbcp_LLL.Bugbear %}
  # Increase from default of `{{ rbcp_LLL.Default }}`
  # Based on https://github.com/PyCQA/flake8-bugbear#opinionated-warnings (`B950`)
  {%- endif %}
  Max: {{ rbcp_LLL.Max }}
{%- set MBL = 'Metrics/BlockLength' %}
{{ MBL }}:
  {%- set rbcp_MBL = rubocop.Cops.get(MBL) %}
  ExcludedMethods:
    {%- for method in rbcp_MBL.ExcludedMethods %}
    - {{ method }}
    {%- endfor %}

{%- if rubocop.AllCops %}

# General settings across all cops in this formula
AllCops:
  {#- This is purposefully simplistic for the time being,
      until (if ever) more advanced configuration is necessary #}
  {%- if rubocop.AllCops.Exclude %}
  # Files to ignore completely
  Exclude:
    {%- for path in rubocop.AllCops.Exclude %}
    - {{ path }}
    {%- endfor %}
  {%- endif %}
{%- endif %}

# Any offenses that should be fixed, e.g. collected via. `rubocop --auto-gen-config`
{%- for cop, config in rubocop.Cops.items() if cop not in [LLL, MBL] %}
{{ cop }}:
  {#- This is purposefully simplistic for the time being,
      until (if ever) more advanced configuration is necessary #}
  {%- for k, v in config.items() %}
  {{ k }}: {{ v }}
  {%- endfor %}
{%- endfor %}
